CREATE TABLE platform_plans
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    price      DECIMAL(19, 4)                          NOT NULL,
    CONSTRAINT pk_platform_plans PRIMARY KEY (id)
);

CREATE TABLE tenant_platform_plans
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    tenant_id    BIGINT                                  NOT NULL,
    plan_id      BIGINT                                  NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    start_date   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    end_date     TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    suspended_by BIGINT,
    suspended_at TIMESTAMP(6) WITHOUT TIME ZONE,
    archived_by  BIGINT,
    archived_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_tenant_platform_plans PRIMARY KEY (id)
);

ALTER TABLE tenant_platform_plans
    ADD CONSTRAINT FK_TENANT_PLATFORM_PLANS_ON_ARCHIVED_BY FOREIGN KEY (archived_by) REFERENCES users (id);

ALTER TABLE tenant_platform_plans
    ADD CONSTRAINT FK_TENANT_PLATFORM_PLANS_ON_PLAN FOREIGN KEY (plan_id) REFERENCES platform_plans (id);

ALTER TABLE tenant_platform_plans
    ADD CONSTRAINT FK_TENANT_PLATFORM_PLANS_ON_SUSPENDED_BY FOREIGN KEY (suspended_by) REFERENCES users (id);

ALTER TABLE tenant_platform_plans
    ADD CONSTRAINT FK_TENANT_PLATFORM_PLANS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE customer_products
DROP
COLUMN currency;

ALTER TABLE customer_products
DROP
COLUMN price;

ALTER TABLE reminders
DROP
COLUMN retry_count;