CREATE TABLE audit_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id      BIGINT                                  NOT NULL,
    action        AUDIT_ACTION                            NOT NULL,
    resource_type VARCHAR(50)                             NOT NULL,
    resource_id   BIGINT,
    old_value     JSONB,
    new_value     JSONB,
    user_agent    TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE tenants
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    slug          VARCHAR(50)                             NOT NULL,
    company_email VARCHAR(255)                            NOT NULL,
    timezone      VARCHAR(100)                            NOT NULL,
    status        TENANT_STATUS                           NOT NULL,
    archived_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_by    BIGINT,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);

CREATE TABLE user_sessions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT                                  NOT NULL,
    refresh_token_hash     VARCHAR(255)                            NOT NULL,
    issued_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked_at             TIMESTAMP WITHOUT TIME ZONE,
    replaced_by_session_id BIGINT,
    ip_address             VARCHAR(45),
    user_agent             TEXT,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    password_hash     VARCHAR(255)                            NOT NULL,
    role              USER_ROLE                               NOT NULL,
    status            USER_STATUS                             NOT NULL,
    email_verified_at TIMESTAMP WITHOUT TIME ZONE,
    last_login_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by        BIGINT,
    deleted_by        BIGINT,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE tenants
    ADD CONSTRAINT uc_tenants_slug UNIQUE (slug);

ALTER TABLE user_sessions
    ADD CONSTRAINT uc_user_sessions_refresh_token_hash UNIQUE (refresh_token_hash);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

ALTER TABLE tenants
    ADD CONSTRAINT FK_TENANTS_ON_DELETED_BY FOREIGN KEY (deleted_by) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_DELETED_BY FOREIGN KEY (deleted_by) REFERENCES users (id);

ALTER TABLE user_sessions
    ADD CONSTRAINT FK_USER_SESSIONS_ON_REPLACED_BY_SESSION FOREIGN KEY (replaced_by_session_id) REFERENCES user_sessions (id);

ALTER TABLE user_sessions
    ADD CONSTRAINT FK_USER_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);