-- ── Enum types ──────────────────────────────────────────────────────────────
CREATE TYPE audit_action     AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED');
CREATE TYPE tenant_status    AS ENUM ('ACTIVE', 'SUSPENDED', 'ARCHIVED');
CREATE TYPE user_role        AS ENUM ('SUPER_ADMIN', 'TENANT_ADMIN', 'TENANT_USER');
CREATE TYPE user_status      AS ENUM ('PENDING', 'ACTIVE', 'DISABLED', 'DELETED');
CREATE TYPE invitation_role  AS ENUM ('TENANT_ADMIN', 'TENANT_USER');
CREATE TYPE invitation_status AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');

-- ── Tables ───────────────────────────────────────────────────────────────────
CREATE TABLE tenants
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    slug          VARCHAR(50)                             NOT NULL,
    company_email VARCHAR(255)                            NOT NULL,
    timezone      VARCHAR(100)                            NOT NULL,
    status        tenant_status                           NOT NULL,
    archived_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_by    BIGINT,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    tenant_id         BIGINT,
    email             VARCHAR(255)                            NOT NULL,
    password_hash     VARCHAR(255)                            NOT NULL,
    role              user_role                               NOT NULL,
    status            user_status                             NOT NULL,
    email_verified_at TIMESTAMP WITHOUT TIME ZONE,
    last_login_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by        BIGINT,
    deleted_by        BIGINT,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE audit_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id      BIGINT                                  NOT NULL,
    action        audit_action                            NOT NULL,
    resource_type VARCHAR(50)                             NOT NULL,
    resource_id   BIGINT,
    old_value     JSONB,
    new_value     JSONB,
    user_agent    TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE user_invitations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id          BIGINT                                  NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    role               invitation_role                         NOT NULL,
    invited_by_user_id BIGINT                                  NOT NULL,
    token_hash         VARCHAR(255)                            NOT NULL,
    status             invitation_status                       NOT NULL DEFAULT 'PENDING',
    expires_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    accepted_at        TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_invitations PRIMARY KEY (id)
);

CREATE TABLE user_sessions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT                                  NOT NULL,
    refresh_token_hash     VARCHAR(255)                            NOT NULL,
    issued_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked_at             TIMESTAMP WITHOUT TIME ZONE,
    replaced_by_session_id BIGINT,
    ip_address             VARCHAR(45),
    user_agent             TEXT,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id)
);

-- ── Unique constraints ───────────────────────────────────────────────────────
ALTER TABLE tenants
    ADD CONSTRAINT uc_tenants_slug UNIQUE (slug);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_invitations
    ADD CONSTRAINT uc_user_invitations_token_hash UNIQUE (token_hash);

ALTER TABLE user_sessions
    ADD CONSTRAINT uc_user_sessions_refresh_token_hash UNIQUE (refresh_token_hash);

-- ── Foreign keys ─────────────────────────────────────────────────────────────
ALTER TABLE tenants
    ADD CONSTRAINT fk_tenants_on_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_on_created_by FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_on_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT fk_audit_logs_on_actor FOREIGN KEY (actor_id) REFERENCES users (id);

ALTER TABLE user_invitations
    ADD CONSTRAINT fk_user_invitations_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE user_invitations
    ADD CONSTRAINT fk_user_invitations_on_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users (id);

ALTER TABLE user_sessions
    ADD CONSTRAINT fk_user_sessions_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_sessions
    ADD CONSTRAINT fk_user_sessions_on_replaced_by FOREIGN KEY (replaced_by_session_id) REFERENCES user_sessions (id);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX idx_invitations_tenant_status ON user_invitations (tenant_id, status);
