ALTER TABLE users ADD COLUMN tenant_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

CREATE TYPE invitation_status AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');
CREATE TYPE invitation_role   AS ENUM ('TENANT_ADMIN', 'TENANT_USER');

CREATE TABLE user_invitations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id          BIGINT                                  NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    role               invitation_role                         NOT NULL,
    invited_by_user_id BIGINT                                  NOT NULL,
    token_hash         VARCHAR(255)                            NOT NULL,
    status             invitation_status                       NOT NULL DEFAULT 'PENDING',
    expires_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    accepted_at        TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_invitations PRIMARY KEY (id)
);

ALTER TABLE user_invitations
    ADD CONSTRAINT uc_user_invitations_token_hash UNIQUE (token_hash);

ALTER TABLE user_invitations
    ADD CONSTRAINT fk_invitations_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE user_invitations
    ADD CONSTRAINT fk_invitations_on_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users (id);

CREATE INDEX idx_invitations_tenant_status ON user_invitations (tenant_id, status);
