spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas-payment-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

app:
  jwt:
    secret: 60000e7866de30227c7ca77a72f62352e3bc26409cfdc55524cd49e791dbb65c
    expiration-seconds: 840000
